//
//  CommonDef.m
//  TG Develop Tools
//
//  Created by toad on 2022/11/17.
//

#import "CommonDef.h"

TG_CONST_VALUE_EXTERN PRE_KEY_FILE = @"file:";
TG_CONST_VALUE_EXTERN PRE_KEY_PATH = @"path:";
TG_CONST_VALUE_EXTERN PRE_KEY_HEX = @"hex:";
TG_CONST_VALUE_EXTERN PRE_KEY_BASE64 = @"base64:";
TG_CONST_VALUE_EXTERN PRE_KEY_DATA = @"data:";
TG_CONST_VALUE_EXTERN PRE_KEY_RES = @"res:";

/// menus
TG_CONST_VALUE_EXTERN TGKEY_MENUS = @"menus";
TG_CONST_VALUE_EXTERN TGKEY_GROUPS = @"groups";
TG_CONST_VALUE_EXTERN TGKEY_URL = @"url";
TG_CONST_VALUE_EXTERN TGKEY_TITLE = @"title";
TG_CONST_VALUE_EXTERN TGKEY_DESCRIPTION = @"description";

TG_CONST_VALUE_EXTERN TGKEY_SUBTITLE = @"subtitle";
TG_CONST_VALUE_EXTERN TGKEY_ICON = @"icon";
TG_CONST_VALUE_EXTERN TGKEY_INFO = @"info";
