# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TGCodeRows' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'PPCounter'
  pod 'ReactiveObjC'
  target 'TGCodeRowsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TGCodeRowsUITests' do
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '12.3'
            config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
            if ['PiwikTracker'].include?target.name
                config.build_settings['SWIFT_VERSION'] = '4.2'
            end
        end
    end
end

