# Uncomment the next line to define a global platform for your project


target 'TGShare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TGShare
 platform :ios, '9.0'
  pod 'ReactiveObjC'
  pod 'AFNetworking'
#  pod 'KissXML'
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SDWebImage'
  pod 'STDbKit'
  pod 'MBProgressHUD'
  pod 'Toast'
  pod 'SDAutoLayout'
end
